source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LILKit_Example', :exclusive => true do
  pod "LILKit", :path => "../"
end

target 'LILKit_Tests', :exclusive => true do
  pod "LILKit", :path => "../"

  
end
